

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'DavaindiaApp' do
  # Override Firebase SDK Version
  # $FirebaseSDKVersion = '7.0.0'
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'
  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'DavaindiaAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

#target 'DavaindiaApp-tvOS' do
#  # Pods for DavaindiaApp-tvOS
#
#  target 'DavaindiaApp-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#end
